const QUESTION_COUNT = 25;
const TEST_SECONDS = 30 * 60;
const STORAGE_KEY = 'rasad_mentor_test_v1';

const CATEGORIES = {
  tech: {name:'Texnik arxitektura', color:'#216df3', quota:5},
  ai: {name:'SI va ma’lumotlar', color:'#7c3aed', quota:5},
  domain: {name:'Iqtisodiy soha', color:'#0891b2', quota:4},
  business: {name:'Biznes', color:'#0f9f6e', quota:4},
  legal: {name:'Huquq va xavfsizlik', color:'#d97706', quota:4},
  pitch: {name:'Pitch va demo', color:'#e11d48', quota:3}
};

const questionBank = [
// ==================== TEXNIK ARXITEKTURA — 20 ====================
{ id:'T01',category:'tech',difficulty:'O‘rta',q:'RASAD frontend qismi uchun TZda tavsiya etilgan asosiy texnologik kombinatsiya qaysi?',o:['Vue 3 + TypeScript + Pinia + Vue Router','PHP + jQuery + Bootstrap 3','Java Swing + SQLite','C# WinForms + Access'],a:0,e:'RASAD uchun Vue 3, TypeScript, Pinia va Vue Router komponentli, tiplangan va keyinchalik kengayadigan frontend sifatida belgilangan.'},
{ id:'T02',category:'tech',difficulty:'Oson',q:'RASAD server qismi uchun qaysi texnologiya tavsiya etilgan?',o:['Python + FastAPI','Ruby on Rails','Laravel + PHP','Spring MVC + JSP'],a:0,e:'FastAPI Python ekotizimidagi SI va ma’lumotlar bilan integratsiya qilish uchun qulay, tez va tiplangan API qatlamini beradi.'},
{ id:'T03',category:'tech',difficulty:'O‘rta',q:'Nega API manzillarini /api/v1/ ko‘rinishida versiyalash kerak?',o:['Keyingi API versiyalarida eski integratsiyalarni buzmaslik uchun','URLni uzunroq qilish uchun','Brauzer keshini o‘chirish uchun','PostgreSQL jadval nomlarini yashirish uchun'],a:0,e:'API versiyalash orqaga moslikni boshqaradi. /api/v2/ paydo bo‘lsa, v1 ishlatayotgan mijozlar darhol buzilmaydi.'},
{ id:'T04',category:'tech',difficulty:'Qiyin',q:'Katta hajmdagi tahlilni oddiy HTTP so‘rovi ichida emas, fon vazifasi sifatida bajarishning asosiy sababi nima?',o:['Uzoq hisoblashni web so‘rovdan ajratib, timeout va bloklanishni kamaytirish','CSSni tezroq yuklash','Parolni xeshlash','MapLibre ranglarini boshqarish'],a:0,e:'Job queue va workerlar uzoq SI/tahlil vazifalarini asinxron bajaradi, API esa foydalanuvchiga vazifa holatini qaytaradi.'},
{ id:'T05',category:'tech',difficulty:'O‘rta',q:'PostGIS RASADda asosan nima uchun kerak?',o:['Hudud geometriyasi va geografik so‘rovlarni bajarish uchun','Parollarni saqlash uchun','SI modelini o‘qitish uchun','PDF fayl yaratish uchun'],a:0,e:'PostGIS PostgreSQLga fazoviy ma’lumot turlari va geografik operatsiyalarni qo‘shadi; xarita va hududiy tahlil uchun mos.'},
{ id:'T06',category:'tech',difficulty:'O‘rta',q:'Redisdan RASADda qaysi vazifa uchun foydalanish eng mantiqiy?',o:['Tezkor kesh va vazifalar navbati uchun','Asosiy uzoq muddatli ma’lumotlar bazasi sifatida','GeoJSON chizish uchun','Frontend komponentlarini kompilyatsiya qilish uchun'],a:0,e:'Redis tezkor kesh, sessiya yoki queue broker kabi qisqa muddatli tezkor vazifalar uchun mos; asosiy relational baza PostgreSQL.'},
{ id:'T07',category:'tech',difficulty:'Qiyin',q:'DEV, STAGING va PRODUCTION muhitlarini ajratishning eng muhim foydasi qaysi?',o:['Test va ishlab chiqishdagi o‘zgarishlarni ishchi tizimdan izolyatsiya qilish','Bir xil ma’lumotni uch marta saqlash','Foydalanuvchi sonini avtomatik oshirish','Model aniqligini kafolatlash'],a:0,e:'Muhitlarni ajratish xavfsiz deploy, test va qabul jarayonini ta’minlaydi; production ma’lumotlari developmentga ko‘chirilmasligi kerak.'},
{ id:'T08',category:'tech',difficulty:'O‘rta',q:'Alembic RASAD arxitekturasida qanday vazifani bajaradi?',o:['Ma’lumotlar bazasi sxemasi migratsiyalarini boshqaradi','SI modelini kalibrlaydi','Xarita qatlamlarini chizadi','CSVni PDFga aylantiradi'],a:0,e:'Alembic SQLAlchemy bilan DB sxema o‘zgarishlarini versiyalash va boshqarish uchun ishlatiladi.'},
{ id:'T09',category:'tech',difficulty:'Qiyin',q:'RASADda “service abstraction” orqali mock ma’lumotni keyinchalik haqiqiy FastAPI bilan almashtirish nima beradi?',o:['UI kodini qayta yozmasdan ma’lumot manbasini almashtirish imkonini','Har bir sahifani alohida domen qilishni','Xavf ballini tasodifiy generatsiya qilishni','Modelni brauzerda o‘qitishni'],a:0,e:'UI komponentlari servis interfeysiga bog‘lanadi; mock va real API bir xil kontrakt orqali almashinadi.'},
{ id:'T10',category:'tech',difficulty:'O‘rta',q:'RASADdagi markazlashgan loglash uchun qaysi yechimlar mos?',o:['Loki, ELK yoki OpenSearch','Excel va PowerPoint','Figma va Canva','NumPy va Pandas'],a:0,e:'Loki/ELK/OpenSearch ilova va infra loglarini markazlashtirib qidirish va kuzatishni ta’minlaydi.'},
{ id:'T11',category:'tech',difficulty:'Qiyin',q:'RPO ≤ 24 soat nimani anglatadi?',o:['Avariya holatida ko‘pi bilan 24 soatlik ma’lumot yo‘qotilishi qabul qilinishi mumkinligini','Tizim 24 soatda ishga tushishini','Har bir API 24 msda javob berishini','Parol 24 soatda almashtirilishini'],a:0,e:'RPO — Recovery Point Objective. U tiklashda qanchalik eski nuqtaga qaytish mumkinligini, ya’ni maksimal ma’lumot yo‘qotish oynasini ifodalaydi.'},
{ id:'T12',category:'tech',difficulty:'Qiyin',q:'RTO ≤ 4 soat nimani bildiradi?',o:['Avariyadan keyin xizmatni 4 soat ichida tiklash maqsadini','Har 4 soatda backup olishni','API token 4 soat yashashini','Modelni 4 soatda qayta o‘qitishni'],a:0,e:'RTO — Recovery Time Objective. Xizmat uzilgach tizimni qayta ishchi holatga keltirish uchun ruxsat etilgan vaqt.'},
{ id:'T13',category:'tech',difficulty:'O‘rta',q:'Dashboard va hududiy yig‘ma ko‘rsatkichlar uchun Redis keshi qo‘llansa, TTL nima uchun kerak?',o:['Keshdagi eskirgan ma’lumotning cheksiz saqlanib qolmasligi uchun','Parol uzunligini belgilash uchun','Xarita masshtabini cheklash uchun','CSS animatsiya vaqtini o‘zgartirish uchun'],a:0,e:'TTL kesh yozuvining amal qilish muddatini belgilaydi va ma’lumot eskirib qolishini nazorat qiladi.'},
{ id:'T14',category:'tech',difficulty:'O‘rta',q:'RASADning asosiy relational ma’lumotlar bazasi sifatida qaysi tizim tavsiya etilgan?',o:['PostgreSQL','MongoDB faqat','Microsoft Access','Firebase Realtime Database faqat'],a:0,e:'PostgreSQL kuchli tranzaksiya, relational aloqa va PostGIS kengaytmasi sababli asosiy baza sifatida mos.'},
{ id:'T15',category:'tech',difficulty:'Qiyin',q:'“Immutable audit log” g‘oyasining maqsadi nima?',o:['Muhim audit yozuvlarini oddiy foydalanuvchi tomonidan o‘zgartirish yoki o‘chirishni cheklash','Loglarni har kuni avtomatik tozalash','Faqat admin kirishi uchun barcha loglarni yashirish','Model natijalarini anonim qilish'],a:0,e:'Auditning ishonchliligi uchun tarix o‘zgarmasligi kerak; kim, qachon, nima qilgani keyinchalik tekshiriladi.'},
{ id:'T16',category:'tech',difficulty:'Qiyin',q:'Frontendda butun RASADni bitta monolit komponentga yozmaslikning asosiy sababi nima?',o:['Qayta foydalanish, testlash va texnik xizmatni yengillashtirish','Brauzerda rang ko‘proq chiqishi','Server RAMini nolga tushirish','GeoJSONni avtomatik yangilash'],a:0,e:'Komponentli arxitektura mas’uliyatlarni ajratadi, kodni boshqariladigan va testlanadigan qiladi.'},
{ id:'T17',category:'tech',difficulty:'O‘rta',q:'Prometheus + Grafana juftligi RASADda asosan qaysi vazifa uchun?',o:['Texnik monitoring va metrikalarni vizual kuzatish','SI modelini yaratish','Parolni shifrlash','PDF eksport'],a:0,e:'Prometheus metrikalarni yig‘adi, Grafana ularni dashboardlarda ko‘rsatadi.'},
{ id:'T18',category:'tech',difficulty:'Qiyin',q:'RASADda standart API xatosi strukturasi bo‘lishi nima uchun muhim?',o:['Frontend va integratsiyalar xatolarni izchil qayta ishlashi uchun','Har bir xatoda serverni qayta ishga tushirish uchun','Model aniqligini oshirish uchun','Xaritani offline qilish uchun'],a:0,e:'Standart error code va message frontend, log va integratsiyalarda xatolarni bir xil usulda boshqarishga yordam beradi.'},
{ id:'T19',category:'tech',difficulty:'O‘rta',q:'RASAD xaritasi uchun noto‘g‘ri, qo‘lda chizilgan siluet o‘rniga GeoJSON ishlatishning foydasi nima?',o:['Ma’muriy hudud chegaralarini real geometriya asosida interaktiv ishlatish','Har bir hududga tasodifiy rang berish','Xavf ballini avtomatik hisoblash','Foydalanuvchini autentifikatsiya qilish'],a:0,e:'GeoJSON hudud geometriyasini standart formatda beradi; hover, click va fazoviy tahlil uchun to‘g‘ri asos yaratadi.'},
{ id:'T20',category:'tech',difficulty:'Qiyin',q:'CI/CD pipeline ichida “Security Scan” bosqichi qaysi maqsadga xizmat qiladi?',o:['Deploydan oldin bog‘liqliklar va koddagi xavfsizlik muammolarini aniqlash','Dashboard ranglarini tekshirish','Xavf score formulasini tasodifiylashtirish','User rolini avtomatik almashtirish'],a:0,e:'Avtomatlashtirilgan xavfsizlik tekshiruvlari ishlab chiqarishga zaif komponent yoki ma’lum muammo chiqish xavfini kamaytiradi.'},

// ==================== AI VA MA’LUMOTLAR — 20 ====================
{ id:'A01',category:'ai',difficulty:'Oson',q:'RASADdagi Risk Score nimani anglatadi?',o:['Qo‘shimcha ekspert tahliliga ustuvorlik beruvchi analitik bahoni','Rasmiy ravishda qoidabuzarlik tasdig‘ini','Sud qarorini','Korxonaning rasmiy yashirin iqtisodiyot ulushini'],a:0,e:'Risk Score — tahliliy ustuvorlashtirish ko‘rsatkichi; u huquqiy hukm yoki rasmiy yashirin iqtisodiyot ulushi emas.'},
{ id:'A02',category:'ai',difficulty:'Oson',q:'RASADda Risk Score, Confidence va Data Quality o‘rtasidagi to‘g‘ri munosabat qaysi?',o:['Uchala ko‘rsatkich alohida ma’noga ega va bir-biriga tenglashtirilmaydi','Uchovining soni doimo bir xil bo‘lishi kerak','Confidence faqat rang nomi','Data Quality faqat dizayn elementi'],a:0,e:'Xavf bahosi ehtimoliy ustuvorlikni, ishonch darajasi natija ishonchliligini, data quality esa kiruvchi ma’lumot sifatini bildiradi.'},
{ id:'A03',category:'ai',difficulty:'O‘rta',q:'Label mavjud bo‘lmagan ma’lumotlarda noodatiy holatlarni aniqlash uchun TZda qaysi yondashuv tavsiya etilgan?',o:['Isolation Forest','Oddiy HTML form','AES shifrlash','PostGIS buffer'],a:0,e:'Isolation Forest nazoratsiz anomaliya aniqlash uchun mos yondashuvlardan biri sifatida ko‘rsatilgan.'},
{ id:'A04',category:'ai',difficulty:'O‘rta',q:'Tasdiqlangan tarixiy label mavjud bo‘lsa, xavfni tasniflash uchun qaysi modellar mos?',o:['LightGBM yoki XGBoost','Leaflet yoki MapLibre','Nginx yoki Redis','Figma yoki Canva'],a:0,e:'Gradient boosting modellar strukturalangan tabulyar iqtisodiy ma’lumotlarda kuchli baseline va production yechim bo‘la oladi.'},
{ id:'A05',category:'ai',difficulty:'Qiyin',q:'SHAP RASADda nima uchun ishlatilishi mumkin?',o:['Model natijasiga qaysi belgilar qancha hissa qo‘shganini tushuntirish uchun','Ma’lumotni shifrlash uchun','PDF sahifa raqamini qo‘shish uchun','API rate limit uchun'],a:0,e:'SHAP feature contributionni hisoblab, “nega bu xavf balli chiqdi?” savoliga strukturali izoh beradi.'},
{ id:'A06',category:'ai',difficulty:'Qiyin',q:'Nega LLM RASADda risk ballini o‘zi yaratmasligi kerak?',o:['Ball strukturali model va tekshiriladigan hisobdan kelishi, LLM esa faqat izohlashi kerak','LLM matn yoza olmaydi','LLM faqat xarita chizadi','LLM PostgreSQL o‘rnini bosadi'],a:0,e:'Tekshiriluvchanlik va ishonchlilik uchun ball deterministik/tahliliy pipeline tomonidan hisoblanadi; LLM strukturali natijani tilda tushuntiradi.'},
{ id:'A07',category:'ai',difficulty:'O‘rta',q:'Model drift nimani anglatadi?',o:['Vaqt o‘tishi bilan ma’lumot yoki natija taqsimoti o‘zgarib, model sifati pasayishi mumkinligini','Model faylining boshqa papkaga ko‘chishini','UI rangining o‘zgarishini','Server IP manzilining almashishini'],a:0,e:'Iqtisodiy muhit o‘zgaradi; model o‘rgangan taqsimot yangi real ma’lumotdan farqlansa drift kuzatiladi.'},
{ id:'A08',category:'ai',difficulty:'Qiyin',q:'Modelni qayta o‘qitish uchun eng asosli signal qaysi?',o:['Drift yoki ekspert feedbacki model sifati pasayganini ko‘rsatsa','Har safar foydalanuvchi login qilganda','Har 10 ta xarita bosilganda','CSS fayl yangilanganda'],a:0,e:'Retraining data/model drift, yangi label va real performance degradatsiyasi asosida rejalashtirilishi kerak.'},
{ id:'A09',category:'ai',difficulty:'O‘rta',q:'Data Quality Score past bo‘lsa RASAD nima qilishi kerak?',o:['Natijaning ishonchliligini ehtiyotkor ko‘rsatib, foydalanuvchini ogohlantirishi','Xavf ballini avtomatik 100 qilishi','Ma’lumotni yashirishi va hech narsa ko‘rsatmasligi','Modelni darhol o‘chirishi'],a:0,e:'Past sifat natijani avtomatik inkor qilmaydi, lekin confidence va izohda ehtiyotkorlikni talab qiladi.'},
{ id:'A10',category:'ai',difficulty:'Qiyin',q:'Entity Resolution RASADda qaysi muammoni hal qiladi?',o:['Turli manbalardagi bir xil subyekt yozuvlarini yagona ichki identifikatorga bog‘lash','Model parametrlarini optimallashtirish','Xarita rangini tanlash','Hisobot shriftini o‘zgartirish'],a:0,e:'Bir korxona turli nom yozilishlari bilan kelishi mumkin; entity resolution buni bitta entityga birlashtiradi.'},
{ id:'A11',category:'ai',difficulty:'O‘rta',q:'Feature Registry nimani boshqaradi?',o:['Model ishlatadigan analitik belgilar nomi, formula, manba va versiyasini','Foydalanuvchi parollarini','HTML rang tokenlarini','PDF logotiplarini'],a:0,e:'Feature registry belgilarni qayta ishlab chiqarish va model lineage uchun zarur metadata saqlaydi.'},
{ id:'A12',category:'ai',difficulty:'Qiyin',q:'Model Registryda “ACTIVE” holatiga o‘tishdan oldin qaysi holat mantiqan talab etiladi?',o:['APPROVED','DELETED','UNKNOWN','BROKEN'],a:0,e:'TZ bo‘yicha tekshirilmagan model faol bo‘la olmaydi; review/approval jarayoni mavjud.'},
{ id:'A13',category:'ai',difficulty:'O‘rta',q:'Vaqt qatorlari tahlilida trend, mavsumiylik va qoldiqni ajratish nimaga yordam beradi?',o:['Kutilgan dinamikadan noodatiy og‘ishni aniqlashga','Parolni yangilashga','API tokenni kodlashga','Xarita poligonini soddalashtirishga'],a:0,e:'Time-series decomposition normal trend va seasonal patternni ajratib, residual/anomaliyani ko‘rishga yordam beradi.'},
{ id:'A14',category:'ai',difficulty:'Qiyin',q:'“Peer comparison” uchun eng to‘g‘ri taqqoslash guruhi qaysi?',o:['Bir xil yoki yaqin soha, hudud va o‘lchamdagi taqqoslanadigan subyektlar','Butunlay boshqa sohadagi tasodifiy subyektlar','Faqat eng yirik 3 korxona','Faqat bir kunlik ma’lumot'],a:0,e:'Taqqoslash ma’noli bo‘lishi uchun peer group strukturaviy jihatdan o‘xshash subyektlardan tuziladi.'},
{ id:'A15',category:'ai',difficulty:'Qiyin',q:'Model kalibrovkasi nima uchun kerak?',o:['Model chiqish ballari bilan real ehtimol/ustuvorlik talqinini yaxshiroq moslashtirish uchun','CSS radiusini belgilash uchun','GeoJSON faylini siqish uchun','User rolini ko‘paytirish uchun'],a:0,e:'Kalibrovka score/probabilityni real kuzatilgan natijalar bilan moslashtirish va thresholdlarni asoslashga yordam beradi.'},
{ id:'A16',category:'ai',difficulty:'O‘rta',q:'Graph analysis RASADda qanday foyda beradi?',o:['Subyektlar o‘rtasidagi bog‘lanish va risk kontekstini tahlil qilish','Parolni tiklash','Hisobotni chop qilish','Frontend build qilish'],a:0,e:'Graph yondashuv entitylar va ularning aloqalarini tugun-qirra modeli orqali ko‘rsatadi.'},
{ id:'A17',category:'ai',difficulty:'Qiyin',q:'False positive yuqori bo‘lsa qanday muammo yuz beradi?',o:['Ekspertlar ko‘p asossiz ogohlantirishlarni tekshirib, resurs sarflaydi','Model barcha real xavflarni topadi','Data quality avtomatik 100 bo‘ladi','API tezlashadi'],a:0,e:'Noto‘g‘ri ijobiy signal ko‘pligi analyst fatigue va resurs isrofini keltiradi; precision muhim.'},
{ id:'A18',category:'ai',difficulty:'Qiyin',q:'Top-K precision RASAD uchun nega foydali metrika?',o:['Eng yuqori ustuvorlikdagi K holat orasida nechta haqiqatan muhim ekanini o‘lchaydi','UI animatsiya tezligini o‘lchaydi','DB hajmini o‘lchaydi','Map zoomini o‘lchaydi'],a:0,e:'RASAD ekspert resursini eng yuqori xavfli holatlarga yo‘naltirgani uchun Top-K sifati amaliy jihatdan muhim.'},
{ id:'A19',category:'ai',difficulty:'O‘rta',q:'Data lineage nimani ta’minlaydi?',o:['Natija qaysi manba, transformatsiya va pipeline versiyasidan kelganini kuzatishni','Modelni avtomatik sotishni','Dashboard ranglarini saqlashni','Internet tezligini oshirishni'],a:0,e:'Lineage audit va reproduktivlik uchun “bu raqam qayerdan keldi?” savoliga javob beradi.'},
{ id:'A20',category:'ai',difficulty:'Qiyin',q:'RASAD Risk Engine uchun eng to‘g‘ri konseptual oqim qaysi?',o:['Feature Vector → Rules/Models → Calibration → Risk Score → Explanation','Login → CSS → PDF → Logout','Map → Password → Redis → Logo','CSV → Random number → Verdict'],a:0,e:'Risk Engine bir nechta signal/modelni birlashtirib kalibrlangan risk score va tushuntirish beradi.'},

// ==================== IQTISODIY SOHA — 20 ====================
{ id:'D01',category:'domain',difficulty:'Oson',q:'RASADning asosiy sohaviy vazifasi nima?',o:['Iqtisodiy ma’lumotlardan qo‘shimcha ekspert tahlilini talab qiladigan xavf signallarini aniqlash','Avtomatik jarima yozish','Soliq stavkasini belgilash','Bank hisobini bloklash'],a:0,e:'RASAD qarorni qo‘llab-quvvatlaydi; huquqiy yoki majburiy chorani avtomatik qo‘llamaydi.'},
{ id:'D02',category:'domain',difficulty:'O‘rta',q:'R01 — Faoliyat dinamikasi xavfi nimani ifodalaydi?',o:['Subyekt iqtisodiy ko‘rsatkichlaridagi keskin yoki noodatiy vaqt o‘zgarishini','Faqat geografik manzil xatosini','Faqat login xatosini','Faqat model driftini'],a:0,e:'R01 dinamik ko‘rsatkichlar vaqt bo‘yicha kutilmagan o‘zgarishini tahlil qiladi.'},
{ id:'D03',category:'domain',difficulty:'O‘rta',q:'R02 — Sohaviy og‘ish qaysi holatga tegishli?',o:['Subyektning o‘z sohasi peer guruhidan sezilarli farq qilishiga','Subyekt IP manzili o‘zgarishiga','PDF fayl hajmi oshishiga','User roli almashishiga'],a:0,e:'Sohaviy og‘ish bir xil sektor ichidagi taqqoslashga asoslanadi.'},
{ id:'D04',category:'domain',difficulty:'O‘rta',q:'R03 — Hududiy og‘ish nimani bildiradi?',o:['Subyekt ko‘rsatkichlarining hududiy qonuniyatdan sezilarli farq qilishini','Xarita dizayni buzilganini','Server boshqa davlatda ekanini','Hudud nomi kirillda yozilganini'],a:0,e:'Hududiy benchmarkga nisbatan g‘ayrioddiy ko‘rsatkich R03 risk signaliga kiradi.'},
{ id:'D05',category:'domain',difficulty:'O‘rta',q:'R06 — Ma’lumotlar ziddiyati qachon paydo bo‘ladi?',o:['Turli manbalardagi tegishli ko‘rsatkichlar bir-biriga mos kelmasa','Barcha manbalar bir xil bo‘lsa','User parolini unutsa','Model versiysi yangilansa'],a:0,e:'Cross-source discrepancy alohida xavf turi bo‘lishi mumkin, chunki bir xil entity haqidagi ma’lumotlar zid keladi.'},
{ id:'D06',category:'domain',difficulty:'Qiyin',q:'Nega yuqori risk score “qoidabuzarlik isbotlandi” degani emas?',o:['Risk score statistik/tahliliy signal bo‘lib, yakuniy fakt va huquqiy xulosa ekspert tekshiruvini talab qiladi','Chunki score faqat dizayn elementi','Chunki barcha score 50 dan past bo‘ladi','Chunki model hech qachon ishlamaydi'],a:0,e:'Xavf signali prioritetni ko‘rsatadi; causality va huquqiy xulosa uchun qo‘shimcha dalil va vakolatli tekshiruv zarur.'},
{ id:'D07',category:'domain',difficulty:'Qiyin',q:'Hudud tanlanganda dashboarddagi qaysi ko‘rsatkichlar o‘zgarishi mantiqan to‘g‘ri?',o:['Subyekt soni, xavf taqsimoti, dinamikalar, tarmoqlar va ogohlantirishlar','Faol model versiyasi majburan har safar','Foydalanuvchi ismi','Tizim logotipi'],a:0,e:'Hudud global filter sifatida analitik vidjetlarni qayta hisoblatadi; tizim metama’lumotlari o‘zgarmaydi.'},
{ id:'D08',category:'domain',difficulty:'O‘rta',q:'R04 — Operatsion noodatiylik uchun qaysi misol mos?',o:['Operatsiyalar soni yoki hajmi odatiy diapazondan keskin chiqib ketishi','Foydalanuvchi fon rangini almashtirishi','Serverda yangi papka ochilishi','PDF nomi o‘zgarishi'],a:0,e:'Operatsion anomaliya transaction count, volume yoki periodicity kabi operatsion signalga tegishli.'},
{ id:'D09',category:'domain',difficulty:'O‘rta',q:'R05 — Aloqadorlik xavfi nimaga asoslanadi?',o:['Subyektning boshqa entitylar bilan iqtisodiy/tashkiliy bog‘lanishlari kontekstiga','Faqat telefon ekran o‘lchamiga','Faqat soliq stavkasiga','Faqat user brauzeriga'],a:0,e:'Graph signal boshqa riskli entitylar bilan bog‘lanishlar, umumiy manzil yoki boshqa qonuniy bog‘lovchi belgilar asosida tahlil qilinadi.'},
{ id:'D10',category:'domain',difficulty:'Qiyin',q:'“Bir xil manzil”ning o‘zi yuqori xavfni isbotlaydimi?',o:['Yo‘q, u faqat boshqa omillar bilan birga kontekstual signal bo‘lishi mumkin','Ha, doimo qoidabuzarlikni isbotlaydi','Ha, chunki manzil hech qachon umumiy bo‘lmaydi','Yo‘q, chunki manzil umuman tahlil qilinmaydi'],a:0,e:'Bitta graph feature yakuniy xulosa bermaydi; ko‘p omilli tahlil va ekspert ko‘rigi zarur.'},
{ id:'D11',category:'domain',difficulty:'Qiyin',q:'Nega RASAD “umumiy risk score” bilan birga risk sabablarini ham ko‘rsatishi kerak?',o:['Ekspert signalni tekshira olishi va qaror asosini tushunishi uchun','Score rangini chiroyli qilish uchun','PDF hajmini oshirish uchun','Ma’lumotni yashirish uchun'],a:0,e:'Explainability analyst trust, audit va xato signalni aniqlash uchun muhim.'},
{ id:'D12',category:'domain',difficulty:'O‘rta',q:'R07 — Davriy xavf qaysi analitik yondashuv bilan eng bog‘liq?',o:['Vaqt qatori va mavsumiylikdan og‘ishni tahlil qilish','RBAC','Password hashing','CSS grid'],a:0,e:'Davriy risk vaqt bo‘yicha seasonal pattern va trenddan deviationni kuzatadi.'},
{ id:'D13',category:'domain',difficulty:'O‘rta',q:'R08 — Kompleks xavf nimani anglatadi?',o:['Bir nechta mustaqil xavf signali bir vaqtda yuqori bo‘lishini','Faqat bitta indikatorni','Faqat login urinishlarini','Faqat xaritadagi bitta hududni'],a:0,e:'Kompleks risk turli signal — vaqt, peer, graph, ziddiyat kabi omillar kombinatsiyasiga asoslanadi.'},
{ id:'D14',category:'domain',difficulty:'Qiyin',q:'Hududlar bo‘yicha xavfni taqqoslashda qaysi xatodan saqlanish kerak?',o:['Turli hajmdagi hududlarni faqat xom son bilan taqqoslab noto‘g‘ri xulosa chiqarishdan','Hudud nomini ko‘rsatishdan','Xaritada tooltip ishlatishdan','Filter qo‘llashdan'],a:0,e:'Absolute count population/subject sizega bog‘liq; normallashtirilgan ulush yoki peer context ko‘pincha zarur.'},
{ id:'D15',category:'domain',difficulty:'Qiyin',q:'“Aylanma −68%” signali qanday talqin qilinishi to‘g‘ri?',o:['Kutilgan diapazon va tarixiy/peer kontekst bilan birga baholanishi kerak','Doimo yashirin iqtisodiyot isboti','Doimo model xatosi','Faqat UI dekoratsiyasi'],a:0,e:'O‘zgarish kontekstsiz xulosa bermaydi; mavsumiylik, sektor, bazaviy davr va data quality bilan tekshiriladi.'},
{ id:'D16',category:'domain',difficulty:'O‘rta',q:'RASADning “priority queue” qiymati nimada?',o:['Ekspert resursini eng muhim tahlil holatlariga yo‘naltirishda','Har bir subyektni bir xil chuqurlikda tekshirishda','Barcha scorelarni yashirishda','Faqat grafik chizishda'],a:0,e:'Tizimning amaliy qiymati — katta hajmda ustuvorlashtirish va analyst e’tiborini to‘g‘ri taqsimlash.'},
{ id:'D17',category:'domain',difficulty:'Qiyin',q:'Risk score thresholdlari nega konfiguratsion bo‘lishi kerak?',o:['Real data, model kalibrovkasi va operatsion siyosatga qarab moslashtirish uchun','Har kuni tasodifiy o‘zgartirish uchun','Foydalanuvchini chalg‘itish uchun','Score formulasini yashirish uchun'],a:0,e:'0–39/40–69/70–100 MVP default bo‘lishi mumkin, ammo productionda validatsiya va policy asosida tasdiqlanadi.'},
{ id:'D18',category:'domain',difficulty:'O‘rta',q:'“Ma’lumot sifati 87/100” ko‘rsatkichi nimani anglatishi kerak?',o:['Kirish ma’lumotlari to‘liqligi, to‘g‘riligi, yagonaligi va boshqa sifat mezonlarining yig‘ma bahosini','Subyektning qonuniylik darajasini','Model accuracyini','Hududning iqtisodiy reytingini'],a:0,e:'Data Quality Score — dataset sifati metrikasi, subyekt riskining o‘zi emas.'},
{ id:'D19',category:'domain',difficulty:'Qiyin',q:'Sohaviy benchmark qurishda qaysi yondashuv eng zaif?',o:['Mutlaqo boshqa biznes modellarini bitta peer guruhga aralashtirish','Bir xil faoliyat turini guruhlash','O‘lcham segmentini hisobga olish','Davrni bir xil olish'],a:0,e:'Noto‘g‘ri peer group deviationni sun’iy ravishda oshiradi yoki kamaytiradi.'},
{ id:'D20',category:'domain',difficulty:'O‘rta',q:'RASAD natijasini eng to‘g‘ri amaliy ifoda qaysi?',o:['“Qo‘shimcha ekspert tahlili talab qilinadigan holat”','“Jinoyat isbotlandi”','“Avtomatik jarima belgilandi”','“Subyekt bloklandi”'],a:0,e:'Platforma qarorni qo‘llab-quvvatlaydi va ehtiyotkor, huquqiy jihatdan neytral terminologiya ishlatishi kerak.'},

// ==================== BIZNES — 20 ====================
{ id:'B01',category:'business',difficulty:'Oson',q:'RASADning asosiy mijoz segmentlaridan biri qaysi?',o:['Iqtisodiy risk tahliliga ehtiyoj sezadigan davlat va moliya tashkilotlari','Faqat o‘yin studiyalari','Faqat dizayn agentliklari','Faqat shaxsiy blog egalari'],a:0,e:'RASADning yadro qiymati katta iqtisodiy ma’lumotdan risk signalini topish; davlat, bank, to‘lov va yirik korporativ segmentlarga mos.'},
{ id:'B02',category:'business',difficulty:'O‘rta',q:'RASAD uchun eng mantiqiy monetizatsiya kombinatsiyasi qaysi?',o:['Joriy etish + yillik litsenziya/foydalanish + modul/integratsiya + texnik xizmat','Faqat reklama bannerlari','Faqat bir martalik domen savdosi','Faqat bepul foydalanish'],a:0,e:'B2B/B2G enterprise tizimlarda integratsiya, yillik foydalanish va support kombinatsiyasi barqaror model bo‘lishi mumkin.'},
{ id:'B03',category:'business',difficulty:'O‘rta',q:'Agar davlat soliq organi RASADni xarid qilmasa, texnologik yadro qayerda qayta ishlatilishi mumkin?',o:['Bank, to‘lov operatori, e-commerce va yirik korxonalarda risk/merchant/partner tahlilida','Faqat kompyuter o‘yinida','Faqat rasmlarni tahrirlashda','Faqat matn tarjimasida'],a:0,e:'Yadro — multi-source data, anomaly, graph va explainable risk — boshqa enterprise risk use-caselarga moslashadi.'},
{ id:'B04',category:'business',difficulty:'Qiyin',q:'RASADning mijozga beradigan eng asosiy iqtisodiy qiymati qaysi?',o:['Analitik resursni ustuvor holatlarga yo‘naltirib, qo‘lda tahlil vaqtini kamaytirish','Har bir subyektni avtomatik aybdor deb belgilash','Soliq stavkasini kamaytirish','Internet narxini tushirish'],a:0,e:'Qiymat taklifi — katta ma’lumot ichida e’tibor talab qiladigan holatlarni tez ajratish va sababini ko‘rsatish.'},
{ id:'B05',category:'business',difficulty:'Qiyin',q:'Pilot bosqichining biznes maqsadi nima?',o:['Haqiqiy foydalanuvchi va ma’lumotda qiymat hamda samaradorlik gipotezasini tekshirish','Darhol butun mamlakatga majburiy joriy etish','Faqat logotipni sinash','Faqat investor slaydini tayyorlash'],a:0,e:'Pilot adoption, integration, performance va real operational value bo‘yicha dalil yig‘adi.'},
{ id:'B06',category:'business',difficulty:'O‘rta',q:'Enterprise/B2G mijoz uchun “proof of value” nimani ko‘rsatishi kerak?',o:['RASADning aniq ish jarayonida vaqt, ustuvorlashtirish yoki sifatga o‘lchanadigan ta’sirini','Faqat chiroyli dashboardni','Faqat kod qatorlari sonini','Faqat logotip variantlarini'],a:0,e:'Sotuv uchun texnik demo yetmaydi; real workflow KPI bilan foyda ko‘rsatilishi muhim.'},
{ id:'B07',category:'business',difficulty:'Qiyin',q:'MVPda narxni asossiz aniq raqam bilan aytishdan ko‘ra qaysi yondashuv professionalroq?',o:['Narx modeli va pricing driverlarni ko‘rsatib, pilot/xarid ma’lumotlari asosida validatsiya qilish','Tasodifiy katta summani e’lon qilish','Raqobatchi narxini ko‘chirib olish','Narxni umuman muhokama qilmaslik'],a:0,e:'Validatsiyasiz aniq narx ishonchlilikni pasaytiradi; segment, deployment va modulga qarab pricing modeli asoslanadi.'},
{ id:'B08',category:'business',difficulty:'O‘rta',q:'RASADning raqobat ustunligini eng to‘g‘ri qanday ifodalash mumkin?',o:['Ko‘p manbali tahlil + tushuntiriladigan xavf + aloqadorlik + ekspert nazorati kombinatsiyasi','Faqat ko‘k rangli dizayn','Faqat bitta chart','Faqat CSV import'],a:0,e:'Farqlanish yagona feature emas, integrallashgan analytical workflowda.'},
{ id:'B09',category:'business',difficulty:'Qiyin',q:'TAM/SAM/SOM ko‘rsatkichlari uchun tekshirilmagan bozor summalarini ishlatishning asosiy xavfi nima?',o:['Investor/mentor oldida dalilsiz bozor da’vosi ishonchlilikni tushiradi','UI tezlashadi','Model accuracy oshadi','Xarita to‘g‘ri chiziladi'],a:0,e:'Bozor raqamlari manba va metod bilan asoslanishi kerak; aks holda fakt emas, taxmin bo‘lib qoladi.'},
{ id:'B10',category:'business',difficulty:'O‘rta',q:'B2G/B2B enterprise mahsulotda qaysi xarajat mijoz uchun muhim bo‘lishi mumkin?',o:['Integratsiya, infratuzilma, support va change management','Faqat logo dizayni','Faqat domen nomi','Faqat prezentatsiya shrifti'],a:0,e:'Total cost of ownership deployment, integration, training/support va infratuzilmani qamrab oladi.'},
{ id:'B11',category:'business',difficulty:'Qiyin',q:'“Financial sustainability” savoliga eng kuchli javob nimani qamrab olishi kerak?',o:['Takroriy daromad, xizmat xarajatlari, joriy etish modeli va mijozni ushlab qolish mexanizmini','Faqat foydalanuvchi sonini','Faqat demo ranglarini','Faqat grant miqdorini'],a:0,e:'Barqarorlik recurring revenue va cost-to-serve balansi bilan tushuntiriladi.'},
{ id:'B12',category:'business',difficulty:'O‘rta',q:'RASAD uchun dastlabki “beachhead” mijozni tanlashda qaysi mezon muhim?',o:['Muammo og‘riqli, data mavjud va pilot qarorini tez qabul qila oladigan segment','Eng ko‘p rang ishlatadigan tashkilot','Eng katta ofis binosi','Eng ko‘p Instagram obunachisi'],a:0,e:'Pilotga mos segmentda pain, data access va decision speed bo‘lishi kerak.'},
{ id:'B13',category:'business',difficulty:'Qiyin',q:'RASADning xarid jarayonida eng katta to‘siqlardan biri qaysi bo‘lishi mumkin?',o:['Ma’lumotga kirish, integratsiya, xavfsizlik va procurement talablari','HTML fayl nomi','Logo radiusi','Chart tooltip rangi'],a:0,e:'Enterprise/gov sotuvda data governance va procurement texnik featurelardan tashqari muhim risk hisoblanadi.'},
{ id:'B14',category:'business',difficulty:'O‘rta',q:'“Who pays?” savoliga RASAD uchun to‘g‘ri javob modeli qaysi?',o:['Risk tahlili va qaror qo‘llab-quvvatlashdan bevosita qiymat oladigan tashkilot','Har bir yakuniy fuqaro majburan','Faqat dasturchi','Faqat investor'],a:0,e:'B2B/B2G modelda iqtisodiy foyda oluvchi tashkilot xaridor bo‘ladi.'},
{ id:'B15',category:'business',difficulty:'Qiyin',q:'Customer lock-inni etik va sog‘lom shaklda qanday qurish mumkin?',o:['Integratsiya sifati, workflow qiymati va ma’lumot tarixining foydasi orqali, sun’iy to‘siqlar bilan emas','Ma’lumotni eksport qildirmaslik orqali','Parolni berkitish orqali','Shartnomani tushunarsiz qilish orqali'],a:0,e:'Sustainable retention mahsulot qiymati va switching costning tabiiy operational sabablariga tayanishi kerak.'},
{ id:'B16',category:'business',difficulty:'O‘rta',q:'MVPning asosiy biznes vazifasi nima?',o:['Eng muhim qiymat gipotezasini minimal funksiyalar bilan isbotlash','Barcha production funksiyalarni bir kunda qurish','Faqat 100 ta slayd tayyorlash','Faqat reklama qilish'],a:0,e:'MVP to‘liq product emas; core value va user flow ishlashini isbotlaydi.'},
{ id:'B17',category:'business',difficulty:'Qiyin',q:'Pilot KPI uchun qaysi ko‘rsatkich RASADga eng mazmunli?',o:['Ekspert tahlil vaqtining qisqarishi va top-priority holatlarning sifati','Logo ko‘rishlar soni','CSS fayl hajmi','Server papkalari soni'],a:0,e:'Operational KPI productning real analyst workflowga ta’sirini o‘lchashi kerak.'},
{ id:'B18',category:'business',difficulty:'O‘rta',q:'“Why now?” savoliga RASAD nuqtai nazaridan qaysi argument mantiqiy?',o:['Ma’lumot hajmi va integratsiya imkoniyatlari oshgani sari qo‘lda tahlil masshtablanmaydi','Chunki barcha eski tizimlar ishlamay qolgan','Chunki SI hamma qarorni almashtiradi','Chunki xarita moda bo‘ldi'],a:0,e:'Data volume o‘sishi prioritization va avtomatlashtirilgan tahlilga ehtiyojni kuchaytiradi.'},
{ id:'B19',category:'business',difficulty:'Qiyin',q:'RASADni “platforma” deb atash qachon asosli?',o:['Bir nechta data source, risk modul, user role va use-caselar yagona yadro orqali kengaytirilsa','Faqat bitta statik HTML bo‘lsa','Faqat bitta chart bo‘lsa','Faqat landing page bo‘lsa'],a:0,e:'Platforma tushunchasi modul, integratsiya va qayta ishlatiladigan core capabilityga tayanadi.'},
{ id:'B20',category:'business',difficulty:'O‘rta',q:'Enterprise sotuvda “integration service” alohida daromad manbai bo‘lishi mumkinmi?',o:['Ha, chunki har bir mijozning data source va infratuzilmasi moslashtirishni talab qilishi mumkin','Yo‘q, integratsiya hech qachon xarajat qilmaydi','Faqat mobil ilovada','Faqat demo rejimida'],a:0,e:'Integratsiya enterprise mahsulotlarda real implementation effort bo‘lib, pricing tarkibiga kirishi mumkin.'},

// ==================== HUQUQ VA XAVFSIZLIK — 20 ====================
{ id:'L01',category:'legal',difficulty:'Oson',q:'RASADning yakuniy qaror modelida inson ekspertining roli qanday?',o:['Avtomatik tahlilni ko‘rib chiqib, yakuniy operatsion qarorni vakolat doirasida qabul qiladi','Model natijasini hech tekshirmasdan tasdiqlaydi','Faqat dizaynni ko‘radi','Faqat parol yaratadi'],a:0,e:'Human-in-the-loop RASADning markaziy tamoyili: SI qarorni qo‘llab-quvvatlaydi, inson o‘rnini bosmaydi.'},
{ id:'L02',category:'legal',difficulty:'O‘rta',q:'RBAC nimani anglatadi?',o:['Ruxsatlarni foydalanuvchi roli asosida boshqarishni','Risk ballini kalibrlashni','Xaritani bo‘yashni','Model driftini'],a:0,e:'Role-Based Access Control — administrator, tahlilchi, rahbar, auditor kabi rollarga ruxsatlarni biriktiradi.'},
{ id:'L03',category:'legal',difficulty:'Qiyin',q:'ABAC RASADda qachon RBACga qo‘shimcha foyda beradi?',o:['Ruxsat hudud, tashkilot yoki boshqa atributga ham bog‘liq bo‘lsa','Faqat rang tanlashda','Faqat CSV eksportda','Faqat logo ko‘rsatishda'],a:0,e:'Attribute-Based Access Control role tashqari region, organization, data sensitivity kabi atributlarni ham hisobga oladi.'},
{ id:'L04',category:'legal',difficulty:'O‘rta',q:'Protected identifierni default holatda maskalashning maqsadi nima?',o:['Keraksiz maxfiy ma’lumot ekspozitsiyasini kamaytirish','Model aniqligini oshirish','Chartni tezlashtirish','PDF hajmini kamaytirish'],a:0,e:'Least-privilege va privacy-by-design tamoyiliga ko‘ra foydalanuvchi faqat vakolati yetadigan ma’lumotni ko‘radi.'},
{ id:'L05',category:'legal',difficulty:'Qiyin',q:'Audit logda qaysi kombinatsiya eng muhim?',o:['Kim, qachon, nima qildi, qaysi obyekt, eski/yangi qiymat','Faqat foydalanuvchi ismi','Faqat brauzer turi','Faqat ekran o‘lchami'],a:0,e:'Audit trail harakatni kontekst bilan reproduksiya va tekshirish uchun yetarli metadata saqlashi kerak.'},
{ id:'L06',category:'legal',difficulty:'O‘rta',q:'Parollarni ma’lumotlar bazasida qanday saqlash kerak?',o:['Kuchli parol xeshlash algoritmi bilan, plaintext emas','Oddiy matnda','HTML commentda','URL queryda'],a:0,e:'Plaintext parol katta xavfsizlik xatosi; maxsus password hashing algoritmlari qo‘llanadi.'},
{ id:'L07',category:'legal',difficulty:'O‘rta',q:'API token, DB password va JWT secretni kod ichiga yozish nega noto‘g‘ri?',o:['Kod tarqalishi bilan sirlar oshkor bo‘lishi mumkin','Kod qisqa bo‘lib qoladi','Model sekinlashadi','Xarita ishlamaydi'],a:0,e:'Secrets alohida secret manager yoki himoyalangan environment orqali boshqarilishi kerak.'},
{ id:'L08',category:'legal',difficulty:'Qiyin',q:'“Data minimization” tamoyili nimani talab qiladi?',o:['Maqsad uchun zarur bo‘lgan eng kam ma’lumotni qayta ishlashni','Mumkin bo‘lgan barcha ma’lumotni yig‘ishni','Ma’lumotni hech qachon o‘chirmaslikni','Barcha foydalanuvchiga to‘liq access berishni'],a:0,e:'Privacy va governance doirasida maqsadga aloqasiz ma’lumotni yig‘ish xavfni oshiradi.'},
{ id:'L09',category:'legal',difficulty:'Qiyin',q:'RASAD demo ma’lumotlari uchun eng xavfsiz yondashuv qaysi?',o:['Sintetik, real shaxs yoki korxonani identifikatsiya qilmaydigan ma’lumot ishlatish','Real STIR va real shaxslarni ochiq ko‘rsatish','Internetdan tasodifiy shaxsiy ma’lumot yig‘ish','Real bank tranzaksiyalarini nusxalash'],a:0,e:'Demo uchun sintetik dataset privacy va noto‘g‘ri real da’volarni oldini oladi.'},
{ id:'L10',category:'legal',difficulty:'O‘rta',q:'“Mazkur baho avtomatik tahlil natijasi bo‘lib, yakuniy huquqiy xulosa hisoblanmaydi” degan ogohlantirish nima uchun kerak?',o:['Avtomatik score bilan huquqiy hukm o‘rtasidagi chegarani aniq ko‘rsatish uchun','Faqat joy to‘ldirish uchun','Modelni tezlashtirish uchun','Xarita rangini o‘zgartirish uchun'],a:0,e:'Bu UIda decision-support rolini to‘g‘ri kommunikatsiya qiladi va foydalanuvchining scorega ortiqcha ishonishini kamaytiradi.'},
{ id:'L11',category:'legal',difficulty:'Qiyin',q:'Least privilege tamoyili nimani bildiradi?',o:['Har bir foydalanuvchiga vazifasi uchun zarur minimal ruxsat berishni','Barcha foydalanuvchiga admin berishni','Parolni hammaga bir xil qilishni','Auditni o‘chirishni'],a:0,e:'Minimal privilege breach impactni va ichki xatolarni cheklaydi.'},
{ id:'L12',category:'legal',difficulty:'O‘rta',q:'TLS RASADda asosan nimani himoya qiladi?',o:['Tarmoq orqali uzatilayotgan ma’lumotni','Diskdagi backupni avtomatik','Model og‘irliklarini kalibrlashni','GeoJSON rangini'],a:0,e:'TLS transport qatlamida client-server trafikini shifrlaydi.'},
{ id:'L13',category:'legal',difficulty:'Qiyin',q:'Retention policy nima uchun kerak?',o:['Har bir ma’lumot turini qancha saqlash, arxivlash va qachon o‘chirishni belgilash uchun','Xarita zoomini saqlash uchun','Faqat login vaqtini belgilash uchun','Model accuracyni oshirish uchun'],a:0,e:'Retention legal, privacy, storage va operational talablarni muvozanatlashtiradi.'},
{ id:'L14',category:'legal',difficulty:'Qiyin',q:'Production ma’lumotini DEV muhitiga to‘g‘ridan-to‘g‘ri ko‘chirish nega xavfli?',o:['DEV nazorati odatda yumshoqroq bo‘lib, maxfiy ma’lumot ekspozitsiyasi oshadi','CSS buziladi','Chartlar ko‘payib ketadi','Vue ishlamay qoladi'],a:0,e:'Development muhitida real protected data ishlatish privacy va security riskini oshiradi; anonymized/synthetic data afzal.'},
{ id:'L15',category:'legal',difficulty:'O‘rta',q:'Incident response ketma-ketligining mantiqiy ko‘rinishi qaysi?',o:['Aniqlash → izolyatsiya → tahlil → bartaraf etish → tiklash → hisobot','Hisobot → logo → CSS → backup','Login → map → logout → delete','Deploy → forget → ignore'],a:0,e:'Incident response avval zarar tarqalishini to‘xtatib, sababni tahlil qilish va tiklash bilan yakunlanadi.'},
{ id:'L16',category:'legal',difficulty:'Qiyin',q:'Model versiyasi va data versiyasini hisobotda ko‘rsatish qaysi prinsipni kuchaytiradi?',o:['Reproduktivlik va auditabilityni','Faqat dizayn izchilligini','Faqat marketingni','Faqat eksport tezligini'],a:0,e:'Bir xil hisobotning qaysi model/data holatida yaratilganini keyin tekshirish mumkin bo‘ladi.'},
{ id:'L17',category:'legal',difficulty:'O‘rta',q:'Auditor roliga model thresholdini o‘zgartirish huquqi berish to‘g‘rimi?',o:['Yo‘q, auditor odatda kuzatadi va tekshiradi, konfiguratsiyani o‘zgartirmaydi','Ha, auditor barcha admin vazifasini bajaradi','Ha, faqat tunda','Farqi yo‘q'],a:0,e:'Separation of duties audit rolini operatsion konfiguratsiyadan ajratadi.'},
{ id:'L18',category:'legal',difficulty:'Qiyin',q:'Explainability huquqiy/compliance nuqtai nazardan nimaga yordam beradi?',o:['Avtomatik signal sabablarini inson ko‘ra olishi va qarorni tekshira olishi uchun','Modelni yashirish uchun','Loglarni o‘chirish uchun','Parolni soddalashtirish uchun'],a:0,e:'Tushuntiriladigan natija accountability va human reviewni kuchaytiradi.'},
{ id:'L19',category:'legal',difficulty:'O‘rta',q:'Demo rejimida real kompaniya nomlarini riskli deb ko‘rsatish qanday muammo tug‘dirishi mumkin?',o:['Asossiz reputatsion va huquqiy xavf','Chart rangi buziladi','API versiyasi o‘zgaradi','CSS sekinlashadi'],a:0,e:'Shuning uchun demo synthetic entitylar bilan aniq belgilanishi kerak.'},
{ id:'L20',category:'legal',difficulty:'Qiyin',q:'“Privacy by design” RASADda qaysi qarorga mos?',o:['Masking, role-based access, minimal data va auditni tizim boshidan arxitekturaga kiritish','Loyiha oxirida faqat disclaimer qo‘shish','Barcha data ochiq bo‘lishi','Parolni frontend JSga yozish'],a:0,e:'Privacy qo‘shimcha patch emas, data model va access architecturedan boshlanishi kerak.'},

// ==================== PITCH VA DEMO — 20 ====================
{ id:'P01',category:'pitch',difficulty:'Oson',q:'RASADni bir jumlada eng aniq qanday ta’riflash mumkin?',o:['Iqtisodiy xavf signallarini aniqlab, sababini tushuntiradigan va ekspert qarorini qo‘llab-quvvatlaydigan tahliliy platforma','Avtomatik jarima tizimi','Oddiy Excel jadvali','Faqat xarita servisi'],a:0,e:'Bir jumlalik ta’rif mahsulot nima, kimga va qanday qiymat berishini chalkashtirmasligi kerak.'},
{ id:'P02',category:'pitch',difficulty:'O‘rta',q:'Demo uchun “Golden Path”ning eng to‘g‘ri boshlanishi qaysi?',o:['Bosh sahifa → hudud → yuqori ustuvorlikdagi subyekt → subyekt kartasi','Sozlamalar → foydalanuvchi o‘chirish → logout','CSS → README → backend','Audit → backup → secret manager'],a:0,e:'Demo avval umumiy holatni ko‘rsatib, keyin drill-down orqali bitta real use-casega olib borishi kerak.'},
{ id:'P03',category:'pitch',difficulty:'O‘rta',q:'Demo paytida “Nega?” tugmasini ko‘rsatishning asosiy qiymati nima?',o:['Risk score ortidagi omillarni mentor ko‘rishi va SI explainabilityni tushunishi','Faqat animatsiya ko‘rsatish','Faqat ko‘proq tugma bo‘lishi','Faqat vaqt to‘ldirish'],a:0,e:'Explainability RASADning muhim differentiatori va texnik ishonchlilik dalili.'},
{ id:'P04',category:'pitch',difficulty:'Qiyin',q:'Mentor “Bu real ma’lumotmi?” deb so‘rasa eng to‘g‘ri javob nima?',o:['MVPda sintetik demo ma’lumot ishlatilganini, arxitektura real integratsiyaga tayyorligini aniq aytish','Ha deb yolg‘on aytish','Savolni chetlab o‘tish','Modelning o‘zi biladi deyish'],a:0,e:'Halollik va scope aniqligi ishonchni oshiradi; synthetic data demo ekanini yashirish kerak emas.'},
{ id:'P05',category:'pitch',difficulty:'Qiyin',q:'“SI qayerda?” savoliga eng kuchli javob qaysi?',o:['Risk Engine ichida supervised/anomaly/time/graph signallari, kalibrovka va explainability ishlaydi','Dashboard ranglarida','Logo ichida','Faqat chatbotda'],a:0,e:'SI aniq computational pipeline sifatida ko‘rsatilsa, mahsulot “AI-wrapper”ga o‘xshamaydi.'},
{ id:'P06',category:'pitch',difficulty:'O‘rta',q:'Mentor “Nega oddiy BI dashboard yetmaydi?” desa nima deyish kerak?',o:['RASAD faqat vizualizatsiya emas; anomaliya, risk scoring, graph tahlil, explainability va expert feedbackni birlashtiradi','Chunki BI ranglari yoqmaydi','Chunki dashboard hech narsa ko‘rsatmaydi','Chunki BI har doim noqonuniy'],a:0,e:'Farqni feature list emas, intelligent workflow orqali tushuntirish kuchliroq.'},
{ id:'P07',category:'pitch',difficulty:'Qiyin',q:'3 daqiqalik pitchda eng katta xato qaysi?',o:['Texnik detallarni haddan tashqari ko‘paytirib, muammo va qiymatni yo‘qotish','Mahsulot nomini aytish','Demo mavjudligini ko‘rsatish','Muammoni bir jumlada aytish'],a:0,e:'Pitchda vaqt cheklangan; muammo → yechim → farq → qiymat → traction/demo mantiqi saqlanishi kerak.'},
{ id:'P08',category:'pitch',difficulty:'O‘rta',q:'Mentor “Xavf 82/100 nimani anglatadi?” desa eng to‘g‘ri javob?',o:['Bu qo‘shimcha ekspert tahliliga ustuvorlik beruvchi kalibrlanadigan analitik score, huquqiy hukm emas','82% qoidabuzarlik isbotlandi','82% yashirin iqtisodiyot ulushi','82 ta qonun buzilgan'],a:0,e:'Risk score talqini juda aniq bo‘lishi kerak; u rasmiy statistik ulush yoki hukm emas.'},
{ id:'P09',category:'pitch',difficulty:'Qiyin',q:'Mentor “Sizning eng katta texnik riskingiz nima?” desa professional javob qaysi yo‘nalishni tan olishi kerak?',o:['Data sifati, label yetishmasligi va real integratsiya murakkabligini, ularga qarshi DQ/unsupervised/pilot strategiyasini','Hech qanday risk yo‘q deyish','Faqat rang tanlashni','Faqat logotipni'],a:0,e:'Riskni yashirishdan ko‘ra, konkret risk + mitigation ko‘rsatish professionalroq.'},
{ id:'P10',category:'pitch',difficulty:'O‘rta',q:'Mentor “Nega aynan siz?” deganda jamoa javobi nimaga tayanishi kerak?',o:['Texnik, SI, domain, dizayn/biznes kompetensiyalarining vazifaga mos kombinatsiyasiga','Faqat loyiha nomiga','Faqat yoshga','Faqat universitet nomiga'],a:0,e:'Team-market fit real rollar va bajarilgan ish bilan ko‘rsatiladi.'},
{ id:'P11',category:'pitch',difficulty:'Qiyin',q:'Demo ishlamay qolsa eng to‘g‘ri zaxira strategiya qaysi?',o:['Oldindan tayyorlangan stabil demo flow, screenshot/video backup va qisqa texnik tushuntirish','Mentorni ayblash','Internetni kutish va sukut saqlash','Loyihani yopish'],a:0,e:'Demo riskini boshqarish pitch disciplinega kiradi; offline/synthetic fallback muhim.'},
{ id:'P12',category:'pitch',difficulty:'O‘rta',q:'Mentor “Raqobatchidan farqingiz?” desa nimani ko‘rsatish kuchli?',o:['Ko‘p manbali risk pipeline, explanation, graph va human review integratsiyasini','Logo rangi boshqacha ekanini','HTML ishlatganini','Boshqa nom tanlaganini'],a:0,e:'Farqlanish business-relevant capability va workflow darajasida ifodalanadi.'},
{ id:'P13',category:'pitch',difficulty:'Qiyin',q:'“Aniqlik necha foiz?” savoliga real labeled dataset yo‘q bo‘lsa qanday javob berish kerak?',o:['Hozir synthetic MVP ekanini, real accuracy pilotdagi validatsiyada o‘lchanishini aytish va uydirma foiz bermaslik','99.99% deb aytish','100% deb aytish','Savolni inkor qilish'],a:0,e:'Validatsiyasiz accuracy raqami ilmiy jihatdan noto‘g‘ri; metric planini aytish professional.'},
{ id:'P14',category:'pitch',difficulty:'O‘rta',q:'Mentor “Huquqiy xavf-chi?” desa RASADdagi asosiy himoya tamoyili qaysi?',o:['Human-in-the-loop, role access, audit, privacy va score huquqiy hukm emasligi','Barcha qarorni AIga berish','Auditni o‘chirish','Real shaxs ma’lumotini demo qilish'],a:0,e:'Governance dizaynning o‘zida ko‘rsatilishi kerak.'},
{ id:'P15',category:'pitch',difficulty:'Qiyin',q:'“Nima uchun hozir?” savoliga 20 soniyalik kuchli mantiq nima?',o:['Ma’lumot hajmi oshmoqda, qo‘lda tahlil masshtablanmaydi, SI esa ustuvorlashtirish va explainabilityni amaliy qiladi','Chunki hamma AI deyapti','Chunki prezentatsiya tayyor','Chunki xarita chiroyli'],a:0,e:'Why-now texnologik va operational trend bilan bog‘liq bo‘lishi kerak.'},
{ id:'P16',category:'pitch',difficulty:'O‘rta',q:'Golden Path oxirida nima ko‘rsatish RASAD hikoyasini yakunlaydi?',o:['Ekspert qarori va hisobot','Login oynasiga qaytish','CSS kodi','README'],a:0,e:'Flow risk signalidan human decision va auditable outputgacha yetib borishi kerak.'},
{ id:'P17',category:'pitch',difficulty:'Qiyin',q:'Mentor “Agar model adashsa-chi?” desa eng to‘g‘ri javob?',o:['Confidence, data quality, explainability, expert review va feedback loop xato xavfini boshqaradi','Model hech qachon adashmaydi','Adashsa ma’lumotni o‘chiradi','Barcha score 50 qilinadi'],a:0,e:'Reliable AI tizim xatoni inkor qilmaydi; detection, mitigation va human controlni ko‘rsatadi.'},
{ id:'P18',category:'pitch',difficulty:'O‘rta',q:'Demo ekranida “Namoyish ma’lumotlari — sintetik” belgisi nima uchun kerak?',o:['Mentorga ko‘rsatilayotgan raqamlar real davlat statistikasi emasligini aniq qilish uchun','Faqat dizayn uchun','Modelni tezlashtirish uchun','Xarita zoomi uchun'],a:0,e:'Bu fact boundaryni aniq ko‘rsatadi va noto‘g‘ri real-world claimning oldini oladi.'},
{ id:'P19',category:'pitch',difficulty:'Qiyin',q:'Mentor “Qaysi qism eng innovatsion?” desa eng kuchli texnik javob qaysi?',o:['Risk Engine: multi-model signallar + calibration + explanation + expert feedbackning yagona pipelinega birlashishi','Sidebar','Login tugmasi','CSV download'],a:0,e:'Innovatsiya UI emas, analitik yadro va boshqariladigan human-AI workflowda.'},
{ id:'P20',category:'pitch',difficulty:'O‘rta',q:'Pitch yakunida eng yaxshi CTA qaysi?',o:['Pilot uchun aniq hamkor/data use-case bilan keyingi qadamni taklif qilish','Faqat “rahmat” deyish','Yana 20 daqiqa texnik detallar aytish','Raqobatchini tanqid qilish'],a:0,e:'Aniq next step mahsulotning real joriy etishga tayyor fikrlanganini ko‘rsatadi.'}
];

// 120+ label requires at least 120 bank items. We intentionally keep the 100 curated core items above
// and generate 20 additional scenario questions from validated concepts without changing the facts.
const scenarioSeed = [
  ['S01','tech','Qiyin','Dashboarddagi bir widget yangi hudud tanlanganda o‘zgarib, boshqasi eski qiymatda qolmoqda. Eng to‘g‘ri arxitektura yechimi?',['Barcha analitik vidjetlarni yagona global filter state va derivation funksiyalariga bog‘lash','Har widgetga alohida tasodifiy son berish','Sahifani majburan reload qilish','Filterlarni o‘chirib tashlash'],0,'Markazlashgan filter state barcha vidjetlar bir xil kontekst asosida qayta hisoblanishini ta’minlaydi.'],
  ['S02','tech','O‘rta','GeoJSON yuklanmasa, professional fallback qanday bo‘lishi kerak?',['Xato holati, qayta urinish va noto‘g‘ri soxta xarita ko‘rsatmaslik','Tasodifiy poligon chizish','Xatoni yashirish','Boshqa davlat xaritasini ko‘rsatish'],0,'Geografik xatolik analitik ishonchlilikka zarar beradi; noto‘g‘ri fallbackdan ko‘ra aniq error state afzal.'],
  ['S03','ai','Qiyin','Risk 85, confidence past. Interfeys qanday talqin qilishi kerak?',['Yuqori risk signali bor, lekin ma’lumot/model ishonchi pastligi sabab ekspert ehtiyotkor tekshirishi kerak','85 bo‘lsa confidence avtomatik yuqori','Subyekt aybdor','Natija yashiriladi'],0,'Risk va confidence alohida o‘lchovlar; yuqori score past confidence bilan kelishi mumkin.'],
  ['S04','ai','Qiyin','Ekspertlar ko‘p yuqori scoreli holatlarni “Rad etildi” deb belgilamoqda. Eng to‘g‘ri keyingi qadam?',['False positive va driftni tahlil qilib, threshold/modelni qayta validatsiya qilish','Ekspert fikrini o‘chirib tashlash','Scorelarni 100 qilish','Auditni o‘chirish'],0,'Human feedback model monitoring uchun muhim signal va retraining/threshold reviewni boshlashi mumkin.'],
  ['S05','domain','Qiyin','Bir hududda yuqori xavfli holatlar soni ko‘p, lekin subyektlar umumiy soni ham juda katta. Qanday taqqoslash to‘g‘ri?',['Xom son bilan birga normallashtirilgan ulush va peer kontekstni ham ko‘rish','Faqat xom son','Faqat rang','Faqat eng katta bitta subyekt'],0,'Hudud hajmi farqini hisobga olmaslik misleading comparisonga olib keladi.'],
  ['S06','domain','O‘rta','Bir subyekt 12 oyda doim mavsumiy pasayish ko‘rsatgan. Joriy pasayish ham shu diapazonda. Bu nima anglatadi?',['Pasayishning o‘zi anomaliya emas, mavsumiy baseline bilan solishtirish kerak','Doimo yuqori risk','Doimo data xato','Subyektni bloklash kerak'],0,'Seasonalityni hisobga olmaslik false positive yaratadi.'],
  ['S07','business','Qiyin','Mijoz “Bizda allaqachon BI bor” desa RASAD qanday pozitsiyalanadi?',['BI ustiga anomaliya/risk/explainability/human-review analytical layer sifatida','BI ni yomonlash orqali','Faqat boshqa rangdagi BI sifatida','Faqat chat-bot sifatida'],0,'RASAD oddiy dashboard emas, decision-support analytical workflow beradi.'],
  ['S08','business','Qiyin','Pilotdan keyin mijoz renewal qilishi uchun eng kuchli sabab nima?',['RASAD workflowda o‘lchanadigan davomiy qiymat berishi va integratsiya qilingan operatsion jarayonga aylanishi','Faqat logo yoqishi','Faqat grant yutgani','Faqat demo tezligi'],0,'Recurring value recurring revenue uchun asos bo‘ladi.'],
  ['S09','legal','Qiyin','Tahlilchi boshqa hudud ma’lumotini ko‘rmasligi kerak. Faqat role yetarlimi?',['Yo‘q, role bilan birga region atributi bo‘yicha ABAC kerak bo‘lishi mumkin','Ha, barcha tahlilchi hamma hududni ko‘rishi shart','Faqat CSS bilan yashirish yetarli','URLni yashirish yetarli'],0,'Backend authorization region atributini ham tekshirishi kerak; faqat UI hide xavfsizlik emas.'],
  ['S10','legal','Qiyin','Frontend tugmani yashirgan, lekin API ruxsatni tekshirmaydi. Bu xavfsizmi?',['Yo‘q, authorization server tomonida ham majburiy tekshirilishi kerak','Ha, tugma yo‘q bo‘lsa xavfsiz','Faqat mobil telefonda xavfli','Faqat auditor uchun xavfli'],0,'Client UIga ishonib bo‘lmaydi; access control backendda enforce qilinadi.'],
  ['S11','pitch','Qiyin','Demo vaqtida mentor “Bu raqam qayerdan keldi?” desa nimani ochish kerak?',['Risk sababidagi manba, data lineage va model/data versiyasini','Faqat logo','Faqat rang palitrasini','Faqat README'],0,'Traceability RASAD ishonchliligining muhim qismi.'],
  ['S12','pitch','O‘rta','Mentor “Siz nima sotyapsiz?” desa eng qisqa javob qaysi?',['Risk tahlili va ekspert qarorini tezlashtiradigan enterprise analytical platforma','HTML fayl','Xarita rasmi','AI so‘zi'],0,'Mahsulotni texnologiya emas, mijoz oladigan capability va qiymat bilan ifodalash kerak.'],
  ['S13','tech','Qiyin','API javobi 2 soniyadan uzoq, lekin hisob 1 daqiqa davom etadi. Eng to‘g‘ri UX?',['Vazifani queuega yuborib job status/progress ko‘rsatish','Brauzerni 1 daqiqa muzlatish','Server timeoutni cheksiz qilish','Natijani tasodifiy ko‘rsatish'],0,'Uzoq vazifa asinxron bajarilib, foydalanuvchi progress olishi kerak.'],
  ['S14','ai','Qiyin','Model accuracy yuqori, lekin high-risk top 20 ichida ko‘p xato. Bu RASAD uchun yetarlimi?',['Yo‘q, Top-K precision kabi operatsion metrikani ham baholash kerak','Ha, umumiy accuracy hamma narsani hal qiladi','Faqat UI muammo','Modelni tekshirish shart emas'],0,'Imbalanced risk use-caseda umumiy accuracy chalg‘itishi mumkin; prioritization sifati muhim.'],
  ['S15','domain','Qiyin','Bir ma’lumot manbasi 3 oy kechikkan. Risk natijasida nima ko‘rsatilishi kerak?',['Data freshness pasaygani va confidencega ta’sir qilishi','Hech narsa','Riskni avtomatik 100','Manbani yashirish'],0,'Stale data tahlilning ishonchliligiga ta’sir qiladi va UIda ko‘rsatilishi kerak.'],
  ['S16','business','O‘rta','Sanoat versiyasiga o‘tishda qaysi xarajat odatda oshadi?',['Integratsiya, xavfsizlik, monitoring va support xarajatlari','Faqat logo xarajati','Faqat prezentatsiya xarajati','Hech biri'],0,'Production-grade mahsulot non-functional talablar va operatsion supportni talab qiladi.'],
  ['S17','legal','Qiyin','Audit logning o‘zi yetarlimi, agar user kimligi ishonchli autentifikatsiya qilinmasa?',['Yo‘q, audit ishonchliligi identity va session nazoratiga ham bog‘liq','Ha, audit har doim yetarli','Faqat rang kerak','Faqat IP yetadi'],0,'Auditdagi “kim” ishonchli bo‘lishi uchun authentication va session control zarur.'],
  ['S18','pitch','Qiyin','Mentor “MVP va production farqi nima?” desa qaysi javob to‘g‘ri?',['MVP core value va demo flow, production esa real integratsiya, security, scale, monitoring va SLA bilan kengayadi','Farqi yo‘q','Faqat rang farqi','Faqat nom farqi'],0,'Scope separation hakathon uchun rejalashtirishning muhim qismi.'],
  ['S19','ai','O‘rta','Data quality yaxshi, lekin model drift aniqlangan. Nima qilish kerak?',['Model performance va yangi taqsimotni qayta validatsiya qilish','Data quality yaxshi bo‘lsa driftni inkor qilish','Auditni o‘chirish','Xaritani almashtirish'],0,'Yaxshi data quality modelning eskirmaganini kafolatlamaydi.'],
  ['S20','business','Qiyin','Enterprise mijoz “data tashqariga chiqmasin” desa qanday deployment varianti kuchli argument bo‘lishi mumkin?',['On-premise yoki mijoz nazoratidagi private infratuzilma varianti','Faqat public demo','Data hammasini ochiq GitHubga joylash','Faqat screenshot berish'],0,'Deployment model security/procurement talabiga moslashishi mumkin.' ]
];
scenarioSeed.forEach(x=>questionBank.push({id:x[0],category:x[1],difficulty:x[2],q:x[3],o:x[4],a:x[5],e:x[6]}));

const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const state = {questions:[],current:0,answers:{},flagged:{},remaining:TEST_SECONDS,timer:null,name:'',showDifficulty:false,shuffleOptions:true,startedAt:null,finished:false};

function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function prepareQuestion(q, shuffleOpts=true){
  const opts=q.o.map((text,i)=>({text,correct:i===q.a}));
  const mixed=shuffleOpts?shuffle(opts):opts;
  return {...q,opts:mixed,correct:mixed.findIndex(x=>x.correct)};
}
function pickBalanced25(){
  let out=[];
  Object.entries(CATEGORIES).forEach(([key,c])=>{
    out.push(...shuffle(questionBank.filter(q=>q.category===key)).slice(0,c.quota));
  });
  return shuffle(out).map(q=>prepareQuestion(q,state.shuffleOptions));
}
function save(){
  if(state.finished) return;
  const serial={questions:state.questions,current:state.current,answers:state.answers,flagged:state.flagged,remaining:state.remaining,name:state.name,showDifficulty:state.showDifficulty,shuffleOptions:state.shuffleOptions,startedAt:state.startedAt};
  localStorage.setItem(STORAGE_KEY,JSON.stringify(serial));
}
function loadSaved(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')}catch{return null}}
function clearSaved(){localStorage.removeItem(STORAGE_KEY)}
function switchScreen(id){$$('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});}
function startNew(){
  state.name=$('#candidateName').value.trim()||'Ishtirokchi';
  state.showDifficulty=$('#showDifficulty').checked;
  state.shuffleOptions=$('#shuffleOptions').checked;
  state.questions=pickBalanced25();state.current=0;state.answers={};state.flagged={};state.remaining=TEST_SECONDS;state.startedAt=Date.now();state.finished=false;
  switchScreen('#quizScreen');buildPalette();renderQuestion();startTimer();save();
}
function resumeTest(){
  const s=loadSaved();if(!s)return;
  Object.assign(state,s,{finished:false,timer:null});
  switchScreen('#quizScreen');buildPalette();renderQuestion();startTimer();
}
function startTimer(){clearInterval(state.timer);updateTimer();state.timer=setInterval(()=>{state.remaining--;updateTimer();if(state.remaining<=0){clearInterval(state.timer);finishTest(true)}else save();},1000)}
function updateTimer(){const m=Math.floor(state.remaining/60),s=state.remaining%60;$('#timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;$('#timer').classList.toggle('warn',state.remaining<=300)}
function buildPalette(){
  const p=$('#questionPalette');p.innerHTML='';state.questions.forEach((_,i)=>{const b=document.createElement('button');b.className='qdot';b.textContent=i+1;b.onclick=()=>{state.current=i;renderQuestion()};p.appendChild(b)});updatePalette();
}
function updatePalette(){
  $$('.qdot').forEach((b,i)=>{b.classList.toggle('current',i===state.current);b.classList.toggle('done',state.answers[i]!==undefined);b.classList.toggle('flagged',!!state.flagged[i])});
  const answered=Object.keys(state.answers).length, flagged=Object.values(state.flagged).filter(Boolean).length,pct=Math.round(answered/QUESTION_COUNT*100);
  $('#answeredCount').textContent=`${answered} / ${QUESTION_COUNT}`;$('#flaggedCount').textContent=flagged;$('#progressPct').textContent=`${pct}%`;document.querySelector('.circular-progress').style.setProperty('--progress',`${pct}%`);
}
function renderQuestion(){
  const q=state.questions[state.current]; if(!q)return;
  $('#qNumber').textContent=state.current+1;$('#categoryBadge').textContent=CATEGORIES[q.category].name;$('#categoryBadge').style.color=CATEGORIES[q.category].color;
  $('#difficultyBadge').textContent=q.difficulty;$('#difficultyBadge').classList.toggle('hidden',!state.showDifficulty);$('#questionText').textContent=q.q;
  const list=$('#optionsList');list.innerHTML='';q.opts.forEach((op,i)=>{const b=document.createElement('button');b.className='option'+(state.answers[state.current]===i?' selected':'');b.innerHTML=`<span class="option-key">${String.fromCharCode(65+i)}</span><span>${op.text}</span>`;b.onclick=()=>selectOption(i);list.appendChild(b)});
  $('#prevBtn').disabled=state.current===0;$('#nextBtn').textContent=state.current===QUESTION_COUNT-1?'Yakunlash':'Keyingi →';$('#flagBtn').classList.toggle('active',!!state.flagged[state.current]);$('#flagBtn').textContent=state.flagged[state.current]?'★ Belgilangan':'☆ Belgilash';updatePalette();
}
function selectOption(i){state.answers[state.current]=i;renderQuestion();save()}
function next(){if(state.current<QUESTION_COUNT-1){state.current++;renderQuestion();save()}else openFinishModal()}
function prev(){if(state.current>0){state.current--;renderQuestion();save()}}
function toggleFlag(){state.flagged[state.current]=!state.flagged[state.current];renderQuestion();save()}
function openFinishModal(){const unanswered=QUESTION_COUNT-Object.keys(state.answers).length;$('#finishModalText').textContent=unanswered?`${unanswered} ta savol javobsiz qolgan. Baribir yakunlaysizmi?`:'Barcha 25 savolga javob berildi. Natijani hisoblaymizmi?';$('#confirmModal').classList.remove('hidden')}
function finishTest(auto=false){
  clearInterval(state.timer);state.finished=true;$('#confirmModal').classList.add('hidden');clearSaved();renderResults(auto);switchScreen('#resultScreen');
}
function calc(){let correct=0;const per={};Object.keys(CATEGORIES).forEach(k=>per[k]={total:0,correct:0});state.questions.forEach((q,i)=>{per[q.category].total++;if(state.answers[i]===q.correct){correct++;per[q.category].correct++}});return{correct,total:QUESTION_COUNT,pct:Math.round(correct/QUESTION_COUNT*100),per}}
function resultLevel(p){if(p>=90)return['A’lo daraja','Mentor savollariga juda kuchli tayyorgarlik. Endi javoblarni 20–30 soniyalik og‘zaki formatda mashq qiling.'];if(p>=75)return['Kuchli tayyorgarlik','Asosiy mantiq yaxshi. Xato yo‘nalishlarni review orqali mustahkamlash kerak.'];if(p>=60)return['Qoniqarli','Bazaviy tushuncha bor, lekin ayrim mentor bloklarida chuqurlik yetishmaydi.'];return['Qayta tayyorlanish kerak','Natija RASADning texnik, biznes va domain asoslarini yana bir bor tizimli ko‘rib chiqishni talab qiladi.']}
function renderResults(auto){
  const r=calc(),[title,summary]=resultLevel(r.pct);$('#scorePct').textContent=`${r.pct}%`;document.querySelector('.score-ring').style.setProperty('--score',`${r.pct}%`);$('#resultTitle').textContent=`${state.name}: ${title}`;$('#resultSummary').textContent=`${r.correct}/${r.total} ta to‘g‘ri javob.${auto?' Vaqt tugagani sabab test avtomatik yakunlandi.':''} ${summary}`;
  const cr=$('#categoryResults');cr.innerHTML='';Object.entries(CATEGORIES).forEach(([k,c])=>{const x=r.per[k],pct=x.total?Math.round(x.correct/x.total*100):0;cr.innerHTML+=`<div class="cat-result"><b>${pct}%</b><span>${c.name}<br>${x.correct}/${x.total} to‘g‘ri</span><div class="bar"><i style="width:${pct}%;background:${c.color}"></i></div></div>`});
  renderReview('all');
}
function renderReview(filter){
  const box=$('#reviewList');box.innerHTML='';state.questions.forEach((q,i)=>{const selected=state.answers[i],ok=selected===q.correct,flag=!!state.flagged[i];if(filter==='wrong'&&ok)return;if(filter==='correct'&&!ok)return;if(filter==='flagged'&&!flag)return;const el=document.createElement('article');el.className=`review-item ${ok?'correct':'wrong'}`;const your=selected===undefined?'Javob berilmagan':q.opts[selected].text;const right=q.opts[q.correct].text;el.innerHTML=`<div class="review-meta"><span>${i+1}-savol</span><span>•</span><span>${CATEGORIES[q.category].name}</span><span>•</span><span>${q.difficulty}</span>${flag?'<span>• ★ Belgilangan</span>':''}</div><h3>${q.q}</h3><div class="answer-row"><b>Sizning javobingiz</b><span>${your}</span></div><div class="answer-row"><b>To‘g‘ri javob</b><span>${right}</span></div><div class="explanation"><b>Himoya izohi:</b> ${q.e}</div>`;box.appendChild(el)});
}
function exportCSV(){
  const rows=[['№','Kategoriya','Savol','Sizning javob','To‘g‘ri javob','Natija']];state.questions.forEach((q,i)=>{const s=state.answers[i];rows.push([i+1,CATEGORIES[q.category].name,q.q,s===undefined?'':q.opts[s].text,q.opts[q.correct].text,s===q.correct?'To‘g‘ri':'Xato'])});
  const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`RASAD_test_${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)
}
function init(){
  const saved=loadSaved();if(saved?.questions?.length===QUESTION_COUNT){$('#resumeBtn').classList.remove('hidden');$('#resumeBtn').textContent=`Davom ettirish — ${Object.keys(saved.answers||{}).length}/25`}
  $('#startBtn').onclick=startNew;$('#resumeBtn').onclick=resumeTest;$('#nextBtn').onclick=next;$('#prevBtn').onclick=prev;$('#flagBtn').onclick=toggleFlag;$('#finishBtnSide').onclick=openFinishModal;$('#cancelFinish').onclick=()=>$('#confirmModal').classList.add('hidden');$('#confirmFinish').onclick=()=>finishTest(false);$('#newTestBtn').onclick=()=>{state.finished=false;switchScreen('#startScreen')};$('#exportBtn').onclick=exportCSV;$('#printBtn').onclick=()=>window.print();$('#themeBtn').onclick=()=>document.body.classList.toggle('dark');
  $$('.review-filter button').forEach(b=>b.onclick=()=>{$$('.review-filter button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderReview(b.dataset.filter)});
  document.addEventListener('keydown',e=>{if(!$('#quizScreen').classList.contains('active')||!$('#confirmModal').classList.contains('hidden'))return;if(['1','2','3','4'].includes(e.key)){const i=+e.key-1;if(state.questions[state.current]?.opts[i])selectOption(i)}else if(e.key==='ArrowRight')next();else if(e.key==='ArrowLeft')prev();else if(e.key.toLowerCase()==='f')toggleFlag()});
  window.addEventListener('beforeunload',save);
  console.info(`RASAD Mentor Test: ${questionBank.length} savol bazasi yuklandi.`);
}
init();
